default:
  navigation:
    - title: "アロマセラピー"
      subtitle: "カテゴリー"
      url: /t/
      items:
        - :title: "エッセンシャルオイル"
          :url: /t/etusensiyaruoiru
        - :title: "エッセンシャルオイルブレンド"
          :url: /t/women/dresses
        - :title: "ディフューザー"
          :url: /t/women/shirts-and-blouses
        - :title: "ブックレット"
          :url: /t/women/sweaters
        - :title: "キャリアオイル"
          :url: /t/women/tops-and-t-shirts
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Men
      subtitle: Categories
      url: /t/men
      items:
        - :title: Shirts
          :url: /t/men/shirts
        - :title: T-shirts
          :url: /t/men/t-shirts
        - :title: Sweaters
          :url: /t/men/sweaters
        - :title: Jackets and Coats
          :url: /t/men/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Sportswear
      subtitle: Categories
      url: /t/sportswear
      items:
        - :title: Tops
          :url: /t/sportswear/tops
        - :title: Sweatshirts
          :url: /t/sportswear/sweatshirts
        - :title: Pants
          :url: /t/sportswear/pants
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: Sportswears
      subtitle: Categories
      url: /t/sportswear
      items:
        - :title: Tops
          :url: /t/sportswear/tops
        - :title: Sweatshirts
          :url: /t/sportswear/sweatshirts
        - :title: Pants
          :url: /t/sportswear/pants
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'